services:
    - name: runtime
      build:
        context: .
        dockerfile: Dockerfile.ca
      env: []
      volumeMounts: []
      limits:
        cpu: 4
        memory: 12
    - name: db
      image: mysql:8
      env:
        MYSQL_ROOT_PASSWORD=example
      volumeMounts: []
      limits:
        cpu: 2
        memory: 8
    - name: phpmyadmin
      image: bitnami/phpmyadmin:5
      env:
        DATABASE_HOST=db
      volumeMounts: []
      limits:
        cpu: 2
        memory: 8
volumes: []
tasks: []
